export enum CatBreed {
  AmericanCurl = 'american-curl',
  Birman = 'birman',
  BlackRagdoll = 'black-ragdoll',
  BritishLonghair = 'british-longhair',
  EgyptianMauCat = 'egyptian-mau-cat',
  ExoticShorthair = 'exotic-shorthair',
  JapaneseBobtail = 'japanese-bobtail',
  MaineCoon = 'maine-coon',
  Munchkin = 'munchkin-cat',
  Persian = 'persian',
  RussianBlue = 'russian-blue-cat',
  ScottishFold = 'scottish-fold',
  SelkirkRexCat = 'selkirk-rex-cat',
  Siamese = 'siamese',
  Siberian = 'siberian',
  Singapura = 'singapura',
  TurkishAngora = 'turkish-angora',
}
